import { getSocket } from './socket';

let peerConnection = null;
let localStream = null;

const configuration = {
    iceServers: [
        { urls: 'stun:stun.l.google.com:19302' },
        { urls: 'stun:global.stun.twilio.com:3478' } // fallback free STUN
    ]
};

/**
 * Initializes and returns the local video/audio stream.
 */
export async function initializeLocalStream() {
    if (!localStream) {
        localStream = await navigator.mediaDevices.getUserMedia({ video: true, audio: true });
    }
    return localStream;
}

export function getLocalStream() {
    return localStream;
}

export async function toggleCamera() {
    if (localStream) {
        const videoTrack = localStream.getVideoTracks()[0];
        if (videoTrack) {
            videoTrack.enabled = !videoTrack.enabled;
            return !videoTrack.enabled; // true = camera off
        }
    }
    return false;
}

export async function toggleMute() {
    if (localStream) {
        const audioTrack = localStream.getAudioTracks()[0];
        if (audioTrack) {
            audioTrack.enabled = !audioTrack.enabled;
            return !audioTrack.enabled; // true = muted
        }
    }
    return false;
}

/**
 * Creates the RTCPeerConnection and wires up tracks and ICE events.
 */
export function createPeerConnection(onRemoteStream) {
    if (peerConnection) {
        peerConnection.close();
    }
    peerConnection = new RTCPeerConnection(configuration);

    if (localStream) {
        localStream.getTracks().forEach(track => {
            peerConnection.addTrack(track, localStream);
        });
    }

    // Capture incoming remote stream
    peerConnection.ontrack = (event) => {
        if (event.streams && event.streams[0]) {
            onRemoteStream(event.streams[0]);
        }
    };

    // Propagate ICE candidates to signaling server
    peerConnection.onicecandidate = (event) => {
        if (event.candidate) {
            const socket = getSocket();
            if (socket) {
                socket.emit('webrtc_ice_candidate', { candidate: event.candidate });
            }
        }
    };

    return peerConnection;
}

/**
 * Caller creates offer and sends to Callee
 */
export async function createOffer() {
    if (!peerConnection) return;
    try {
        const offer = await peerConnection.createOffer();
        await peerConnection.setLocalDescription(offer);
        const socket = getSocket();
        if (socket) {
            socket.emit('webrtc_offer', { sdp: peerConnection.localDescription });
        }
    } catch (err) {
        console.error('[WebRTC] Error creating offer:', err);
    }
}

/**
 * Callee receives offer, attaches, creates answer, sends to Caller
 */
export async function handleReceiveOffer(sdp) {
    if (!peerConnection) return;
    try {
        await peerConnection.setRemoteDescription(new RTCSessionDescription(sdp));
        const answer = await peerConnection.createAnswer();
        await peerConnection.setLocalDescription(answer);
        const socket = getSocket();
        if (socket) {
            socket.emit('webrtc_answer', { sdp: peerConnection.localDescription });
        }
    } catch (err) {
        console.error('[WebRTC] Error handling offer:', err);
    }
}

/**
 * Caller receives answer and completes connection
 */
export async function handleReceiveAnswer(sdp) {
    if (!peerConnection) return;
    try {
        await peerConnection.setRemoteDescription(new RTCSessionDescription(sdp));
    } catch (err) {
        console.error('[WebRTC] Error handling answer:', err);
    }
}

/**
 * Both sides process ICE candidates generated by STUN
 */
export async function handleReceiveCandidate(candidate) {
    if (!peerConnection) return;
    try {
        await peerConnection.addIceCandidate(new RTCIceCandidate(candidate));
    } catch (err) {
        console.error('[WebRTC] Error adding received ice candidate:', err);
    }
}

/**
 * Closes the connection for a specific match (e.g. skinning/disconnecting)
 */
export function closePeerConnection() {
    if (peerConnection) {
        peerConnection.close();
        peerConnection = null;
    }
}

/**
 * Turns off the webcam/mic when exiting video chat feature
 */
export function cleanupLocalStream() {
    if (localStream) {
        localStream.getTracks().forEach(track => track.stop());
        localStream = null;
    }
}
